### ISSUE TITLE
Original clefs for online works

### ISSUE THREAD

**Issue by craigsapp** [TassoInMusicProject/tasso-website#13]
It would be good for you to send me a list of original clefs for all of the currently online works:

http://www.tassomusic.org/census

Then I can work on a display system for the work pages to toggle between modern and original clefs in the incipit/full work shown at the top of the work page, such as on:

http://www.tassomusic.org/work?id=Tas0047m

It will probably involve a button on the incipit navigator bar where the play button currently resides.  And also a keyboard shortcut, such as alt-o, [as is the case on VHV](http://doc.verovio.humdrum.org/commands/alt-o).

**Comment by emilianoricciardi** [comment]
OK, will do.

**Comment by craigsapp** [comment]
Implemented. see issue #23 for notes on keyboard shortcuts to show original clefs.  Probably adding a button to the navigation bar above the incipit would be good, however.
