### ISSUE TITLE
Create musical settings pages for non-Rime poems

### ISSUE THREAD

**Issue by emilianoricciardi** [TassoInMusicProject/tasso-website#15]

**Comment by craigsapp** [comment]
Musical settings lists for Gerusalemme-based settings are now available.

For example:  http://tassomusic.org/settings/?id=Tsg12065

<img width="1142" alt="screen shot 2017-04-07 at 11 19 56 am" src="https://cloud.githubusercontent.com/assets/3487289/24813762/2919ec34-1b84-11e7-94f4-8f16fd355846.png">

**Comment by emilianoricciardi** [comment]
Thanks, Craig! Looks pretty good. We'll need to figure out how to indicate
self-standing pieces and those that are part of cycles, which may also
require us to use smaller fonts/shorter titles...

**Comment by craigsapp** [comment]
Muiscal settings for Aminta and other poems are now available.

For an Aminta example: http://www.tassomusic.org/settings/?id=Tam2031126

<img width="1154" alt="screen shot 2017-04-07 at 8 53 24 pm" src="https://cloud.githubusercontent.com/assets/3487289/24825502/48bd646c-1bd4-11e7-94c8-d21eb92f5342.png">

and a Ecloghe example:   http://www.tassomusic.org/settings/?id=Tec1001

<img width="1149" alt="screen shot 2017-04-07 at 8 52 29 pm" src="https://cloud.githubusercontent.com/assets/3487289/24825491/29ea8ac4-1bd4-11e7-9f6d-076da78dba39.png">

**Comment by craigsapp** [comment]
> Thanks, Craig! Looks pretty good. We'll need to figure out how to indicate
self-standing pieces and those that are part of cycles, which may also
require us to use smaller fonts/shorter titles...

We can discuss that on Monday...
