### ISSUE TITLE
Normalize publication locations

### ISSUE THREAD

**Issue by craigsapp** [TassoInMusicProject/tasso-website#21]
Here are the princeps publisher locations for the musical settings (just the Rime, I think).  The first column is the current entry, and the second is the "normalized" version.  @emilianoricciardi should check the modern city names assigned in the second column below:

```
original                  normalized
Anversa                  Antwerp
Augusta                  Augusta (same)
Bologna                  Bologna (same)
Dresdae                  Dresden
Ferrara                  Ferrara (same)
Firenze                  Florence
Genova                   Genoa
Hamburg                  Hamburg (same)
Jena                     Jena (same)
København, Waltkirch     Copenhagen
Leyda                    XXX
Milano                   Milan
Napoli                   Naples
Norimberga               Nuremberg
Palermo                  Palermo
Parigi                   Paris
Parma                    Parma (same)
Roma                     Rome
Venetia                  Venice
Venezia                  Venice
Venice                   Venice (same)
Venigia                  Venice
Ventia                   Venice
Venzia                   Venice
Verona                   Verona (same)
Vincenti                 XXX
Vineggia                 Venice
Vinegia                  Venice
```

Vincenti is a publisher (from Venice, correct?), so that is an error in the index I can fix as well when adding the normalized publisher loctaions.

The XXX ones I am not sure of:  Leyda might be Leiden.  Also What is "Waltkirch"? is that a second city or a suburb of Copenhagen?

If you check those and add the values for "XXX", then I can insert the normalized locations into the publisher locations in the rime setting index file.

Index file which will be changed (plus Gerusalemma settings index, etc):

https://github.com/TassoInMusicProject/tasso-website/blob/gh-pages/data/indexes/rime-settings.aton

Example entry:

```
@@BEGIN:	RIME_SETTING
@CATALOGNUM:	Trm0327a
@RIMETITLE:	Come cristallo in monte
@SOLERTI:	327
@COMPOSER:	Acelli, Cesare
@COMDATES:	
@PRINCEPSTITLE:	In fiori musicali, libro secondo
@PRINCEPSLOC:	Venetia
@PRINCEPSPUB:	Vincenzi
@PRINCEPSYEAR:	1588
@PRINCEPSRISM:	1588-20
@REPRINTS:	1598-10, 1604-13
@OCLEFS:	
@OTIME:	
@OKEYSIG:	
@NOTE:		
@@END:		RIME_SETTING
```

To such a record, a parameter such as:

```
@NORMLOC:
```

will be added (probably even when the `@PRINCEPSLOC` is the same).  The `@NORMLOC` will be used in the Humdrum metadata records, as well as in the settings lists such as:

http://www.tassomusic.org/settings/?rime=47

which is currently using the princeps edition source spellings.

You can make note of any changes to the above list and then set the Assignee to me.

**Comment by emilianoricciardi** [comment]
Question: should I create such as list in a Word document or should I enter all the normalized spellings in the .aton file?

**Comment by craigsapp** [comment]
You can do it in a Word document and then I will put it into the aton files.  (You can just even write any corrections here and I will collate into the aton files).

**Comment by emilianoricciardi** [comment]
It's all correct except for:

-Vincenti is a publisher, not a place, as you correctly guessed
-Augusta is modern-day Augsburg
-Leyda is indeed Leiden
-Remove Waltkirch after Copenhagen (don't remember why was there, would have to double-check, but we don't need it in the abbreviated lists)

**Comment by craigsapp** [comment]
For Vincenti, here is the entry:

```
@@BEGIN:        RIME_SETTING
@CATALOGNUM:    Trm0379b
@RIMETITLE:     Non si levava ancor l’alba novella
@SOLERTI:       379
@COMPOSER:      Gallo, Vincenzo
@COMDATES:
@PRINCEPSTITLE: Le risa a vicenda. Vaghi e dilettevoli madrigali a cinque voci
@PRINCEPSLOC:   Vincenti
@PRINCEPSPUB:
@PRINCEPSYEAR:  1598
@PRINCEPSRISM:  1598-08
@REPRINTS:
@OCLEFS:
@OTIME:
@OKEYSIG:
@NOTE:
@@END:                          RIME_SETTING
```

What should the `@PRINCEPSLOC` be?  I am setting it to Venice, but that is technically te `@NORMLOC`. (I also moved Vincenti to the `@PRINCEPSPUB` parameter).

**Comment by emilianoricciardi** [comment]
Hi Craig,

the original location and publisher are Venetia and Appresso Giacomo
Vincenti, respectively.

Emiliano

**Comment by craigsapp** [comment]
Hi @emilianoricciardi (that is the Githubbish way of naming people -- I am @craigsapp),

Thanks, I have fixed the record for Trm0379b to:

```
@@BEGIN:        RIME_SETTING
@CATALOGNUM:    Trm0379b
@RIMETITLE:     Non si levava ancor l’alba novella
@SOLERTI:       379
@COMPOSER:      Gallo, Vincenzo
@COMDATES:
@PRINCEPSTITLE: Le risa a vicenda. Vaghi e dilettevoli madrigali a cinque voci
@PRINCEPSLOC:   Venetia
@PRINCEPSPUB:   Appresso Giacomo Vincenti
@PRINCEPSYEAR:  1598
@PRINCEPSRISM:  1598-08
@REPRINTS:
@OCLEFS:
@OTIME:
@OKEYSIG:
@NOTE:
@@END:          RIME_SETTING
```

I will be adding the normalized locations soon (and then look into the normalized publisher names).

**Comment by emilianoricciardi** [comment]
OK. Speaking of which, we need to do this also for the non-Rime settings...

**Comment by craigsapp** [comment]
Yes, I will set up the processing of adding new parameters for this case, and then continue with the Gerusalemme, Aminta, and Other groups (asking you if there is a new publication place not found in the Rime group).

**Comment by craigsapp** [comment]
Princeps publication locations have been added to the aton index files:

https://github.com/TassoInMusicProject/tasso-website/tree/gh-pages/data/indexes

The `rime-settings.aton` index is the only one which contains original spellings based on the location names in the princeps editions.  The Gerusalemme, Aminta and other poem setting sources are actually using the modern place names for the princeps location names (so for those groupings, the `@PRINCEPSLOC` and `@NORMLOC` are the same value).

Here is an example of the settings of Rime 47, which now use the `@NORMLOC` value for the publisher location:

<img width="990" alt="screen shot 2017-04-04 at 7 37 42 pm" src="https://cloud.githubusercontent.com/assets/3487289/24687530/fd1575d4-196e-11e7-846b-29d8e663a5bc.png">

**Comment by craigsapp** [comment]
Also, the princeps location to normalized location mappings are done with the file:

https://github.com/TassoInMusicProject/tasso-website/blob/gh-pages/data/support/normalized-locations.hmd

The first column contains the princeps location and the second column is the normalized (modern) name.  There is one tab character separating each column.  

Updates or changes to the mappings can be made to this file, and then the index files will be updated by running these commands on the command line:

```bash
make normloc
make move
```
