### ISSUE TITLE
Rime 864 verses missing

### ISSUE THREAD

**Issue by craigsapp** [TassoInMusicProject/tasso-website#30]
In the file: https://github.com/TassoInMusicProject/tasso-website/blob/gh-pages/data/indexes/rime-verses.aton

There should be an entry for Rime 862 titled *La bella e vaga man che le sonore corde*.

In other words, there are musical settings for Rime 862, but no verses for it in the verses index file.

You can either add it to the rime-verses.aton file yourself, or email the data to me to add.  Here is an example for Rime 865:

```
@@BEGIN:        RIME
@SOLERTI:       865
@TITLE:         Deh! perch&eacute; amar chi voi con pari affetto
@GENRE:         sonetto
@MANUSRC:       Ts<sub>2</sub>, V<sub>13/TS2</sub>
@PRINTSRC:      22, 22a), 26, 31, 35, 69, 78, 87, 105, 141, 166, 169
@@BEGIN:        VERSES
@VERSE:
        Deh! perch&eacute; amar chi voi con pari affetto
        Non ami e sospirar chi non sospiri,
        E distillare in lacrime i martiri
        Per tal che mai per voi non bagni il petto?
@VERSE:
        E'mpallidir per chi non cangi aspetto,
        E volger gli occhi in cos&iacute; dolci giri
        Ad un crudel ch'in voi non li raggiri
        Com'a suo caro e des&iuml;ato oggetto?
@VERSE:
        S'amor a voglia altrui s'estingue e infiamma,
        Spengete il vostro mal gradito e rio
        E de' begli occhi rasciugate il duolo;
@VERSE:
        E geli il cor gentil per lungo oblio,
        E, se pur dee sentir novella fiamma,
        S'accenda s&iacute;, ma non s'accenda ei solo
@@END:          VERSES
@@END:          RIME
```

**Comment by emilianoricciardi** [comment]
@@BEGIN:        RIME
@SOLERTI:       862
@TITLE:         La bella e vaga man che le sonore
@GENRE:         sonetto
@MANUSRC:       Ts<sub>2</sub>
@PRINTSRC:      22, 22a), 26, 31, 36, 40, 50a), 69, 141, 166, 169
@@BEGIN:        VERSES
@VERSE:
        La bella e vaga man che le sonore
        Corde, or leggiera e presta, or tarda e grave
        Percuote, e suon ne trae vario e soave,
       E 'l dolce canto tuo, che forma Amore,
@VERSE:
        Son l'armi dolci onde piagato egrave il core
        In guisa tal che di morir non pave;
        Ma vago fatto di languir, sol have
        Di risanar, quasi di mal, timore. 
@VERSE:
        Onde per languir sempre, or questa piaga
        Ed or quell'altra col pensier rinnova,
        Vera Vittoria e vera vincitrice,
@VERSE:
        Che rende l'alma di penar s&igrave vaga
        Che quel ch'altrui pi&ugrave nuoce a lei pi&ugrave giova,
        Ne' sospir lieta e ne' martir felice.
@@END:          VERSES
@@END:          RIME

**Comment by craigsapp** [comment]
Added to index file, and dummy variant pages are now online:

http://www.tassomusic.org/variants/?rime=862

<img width="1069" alt="screen shot 2017-04-10 at 10 00 30 am" src="https://cloud.githubusercontent.com/assets/3487289/24873102/8baeebe0-1dd4-11e7-8edb-13ec9dfa3423.png">

**Comment by emilianoricciardi** [comment]
Problem: at line 5 "egrave" is supposed to be rendered as "è" (maybe I
should have added the &?)

On Mon, Apr 10, 2017 at 1:01 PM, Craig Stuart Sapp <notifications@github.com

**Comment by craigsapp** [comment]
Yes, `egrave` should be `&egrave;` (start with `&` and end with `;`.

I fixed it in the rime verses index file (you have to close the TMP tab and open a new one to see the change on the website):

http://www.tassomusic.org/variants/?rime=862

<img width="1062" alt="screen shot 2017-04-10 at 10 21 16 am" src="https://cloud.githubusercontent.com/assets/3487289/24873915/83ea91f4-1dd7-11e7-88f2-cf0b4fbb9671.png">
