### ISSUE TITLE
Possible octave error in Trm0059c

### ISSUE THREAD

**Issue by craigsapp** [TassoInMusicProject/tasso-website#40]
In the Alto part of Trm0059c:

www.tassomusic.org/work/?id=Trm0059c

The vocal range looks suspicious:

<img width="175" alt="screen shot 2017-04-14 at 10 21 31 pm" src="https://cloud.githubusercontent.com/assets/3487289/25061010/f3ea95c6-2160-11e7-9644-c1f21c48e6eb.png">

There are two D3's and then a gap until the next lowest note at G3.  The lowest note of any other part labeled "Alto" current in the TMP database is F3 (but only a few works with alto at the moment).

Perhaps the D3's are supposed to be one octave higher?  Here are the suspicious notes in measure 7:

<img width="1007" alt="screen shot 2017-04-14 at 10 21 38 pm" src="https://cloud.githubusercontent.com/assets/3487289/25061024/86d180e8-2161-11e7-9181-ae19c52e5343.png">

Or maybe this is an interesting word-painting example, since the text is a bit depressed at this point (Non ho vita né core e non son io).

**Comment by emilianoricciardi** [comment]
This is correct....it's a very extreme piece, in the style of seconda prattica (see also dissonance treatment and other large intervals). I have sent you the original part by email.
