### ISSUE TITLE
Trm0047a T m3 editorial accidental?

### ISSUE THREAD

**Issue by craigsapp** [TassoInMusicProject/tasso-website#41]
In measure 4 of the tenor part of Trm0047a, the second note F4 is natural, but perhaps an editorial natural sign should be added above the note to cancel the F# from the previous measure:

http://www.tassomusic.org/work/?id=Trm0047a&k=e3

<img width="820" alt="screen shot 2017-04-15 at 12 42 16 am" src="https://cloud.githubusercontent.com/assets/3487289/25061879/8e0e68fe-2174-11e7-86fe-c6240d843c17.png">

**Comment by emilianoricciardi** [comment]
Yes, adding an editorial natural would be good. It's pretty obvious in the score format, as there is an F natural above it in the Canto, but less so in the extracted part. 

Is the editorial natural missing also in the Finale XML file?

**Comment by craigsapp** [comment]
Done:

<img width="1014" alt="screen shot 2017-04-17 at 5 15 33 pm" src="https://cloud.githubusercontent.com/assets/3487289/25109462/8dda8e66-2391-11e7-81b8-c961365acd03.png">

The Finale XML file does not have it (otherwise it would be converted into the Humdrum file and then displayed in the final SVG image.
