### ISSUE TITLE
Restore "Literary Sources" Pages for Rime Poems

### ISSUE THREAD

**Issue by emilianoricciardi** [TassoInMusicProject/tasso-website#49]

**Comment by craigsapp** [comment]
Fixed.

Example page:

http://www.tassomusic.org/sources/?rime=23

![screen shot 2017-04-17 at 10 51 08 pm](https://cloud.githubusercontent.com/assets/3487289/25116253/69b45844-23c0-11e7-91db-20efaba7a020.png)
