### ISSUE TITLE
Add logos next to institutional project supporters (under "Project Participants")

### ISSUE THREAD

**Issue by emilianoricciardi** [TassoInMusicProject/tasso-website#70]

**Comment by craigsapp** [comment]
Implemented:

http://www.tassomusic.org/about/participants

<img width="813" alt="screen shot 2018-03-21 at 1 45 07 pm" src="https://user-images.githubusercontent.com/3487289/37710351-ab33a43a-2d0d-11e8-81c8-3621dd3397d8.png">

**Comment by craigsapp** [comment]
(clicking on the logos will open a new tab with the institutional website.
