### ISSUE TITLE
Tabs for "About" Page

### ISSUE THREAD

**Issue by emilianoricciardi** [TassoInMusicProject/tasso-website#71]
Add "Introduction to TMP" and "How to use TMP" tabs to "About" page

**Comment by craigsapp** [comment]
Tabs added to about page with commit https://github.com/TassoInMusicProject/tasso-website/commit/865f9c0eca7e665c251c8fe77d58e93509c867cc

The names of the tabs are stored in `_layouts/about.html`, selecting them is controlled in `about/scripts-local.html`.

The introduction page is https://github.com/TassoInMusicProject/tasso-website/blob/gh-pages/about/introduction.md .

The How-to page is https://github.com/TassoInMusicProject/tasso-website/blob/gh-pages/about/howto.md .

Text for the pages are formatted using "Markdown" which is a simplified script for generating HTML text.  Check out the page https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet to see the features and syntax of markdown.
