### ISSUE TITLE
Tabs for "Editorial Guidelines" page

### ISSUE THREAD

**Issue by emilianoricciardi** [TassoInMusicProject/tasso-website#72]
Add "Musical Editions" and "Literary Transcriptions/Variants" tabs to "Editorial Guidelines" page

**Comment by craigsapp** [comment]
This feature was implemented with commit https://github.com/TassoInMusicProject/tasso-website/commit/990b1bc45ed56812937aa56a22f2b85d6dadc94d

The music policies should be placed in the file https://github.com/TassoInMusicProject/tasso-website/blob/gh-pages/about/policies/music.md

And the literary policies should be placed in the file https://github.com/TassoInMusicProject/tasso-website/blob/gh-pages/about/policies/text.md

These two files should use the Markdown syntax: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet
