### ISSUE TITLE
Some lyrics are missing

### ISSUE THREAD

**Issue by craigsapp** [TassoInMusicProject/tasso-website#75]
For example:

http://www.tassomusic.org/work/?id=Trm0023c

**Comment by craigsapp** [comment]
They were set to zero size somehow.  Should now be fixed:

![screen shot 2018-01-26 at 4 39 46 pm](https://user-images.githubusercontent.com/3487289/35466314-969d247c-02b7-11e8-8331-b71dca2660ee.png)

**Comment by emilianoricciardi** [comment]
Ah I see, so now I can proceed with the corrections through Github

On Fri, Jan 26, 2018 at 7:40 PM, Craig Stuart Sapp <notifications@github.com

**Comment by craigsapp** [comment]
Yes, and I fixed the other problem (issue #74) which was caused by a typo when I was preparing the score (so it was not related to this problem and invisible because the name was not placed in the correct position).
