### ISSUE TITLE
Original Clefs display is broken

### ISSUE THREAD

**Issue by craigsapp** [TassoInMusicProject/tasso-website#76]
Probably due to new options interface to verovio.

**Comment by craigsapp** [comment]
There are two separate problems:

(1) If there is no `*oclef` information in the files, then the original clefs cannot be shown.  Maybe in such cases the `o` button should be hidden since it does not do anything.

(2) In the current interface, such as on the page http://www.tassomusic.org/work/?id=Trm0047a, the `o` button will show the original clef, but then when unselecting the `o` button, the original clefs are still shown.  The correct xpath query is being sent to verovio, but verovio seems to be remembering the first xpath query it is given and cannot replace with a new one.

Here is what the `o` button should do (show C clefs for most parts):

<img width="877" alt="screen shot 2018-03-04 at 10 52 36 am" src="https://user-images.githubusercontent.com/3487289/36949191-d7fba930-1f99-11e8-8dc0-6e02576bbef5.png">

Although clicking to turn it off keeps the original clefs:

<img width="904" alt="screen shot 2018-03-04 at 10 53 20 am" src="https://user-images.githubusercontent.com/3487289/36949198-e740ed92-1f99-11e8-9df0-dc118fe5ee23.png">

**Comment by emilianoricciardi** [comment]
Information about clefs and mensuration should be in the settings
spreadsheet. Have you been pulling it from there?

**Comment by craigsapp** [comment]
Not yet.  That involves a two-stage process, which I will work on automating:

(1) Taking data from the Spreadsheet:
      https://docs.google.com/spreadsheets/d/1YcaAQc-mxFFDWyOsT7HOlwZkEqB4rPEuOzXCMTKprMc/edit#gid=1098021743

And then (2) merging it into the ATON file containing the full information for each musical setting.

https://github.com/TassoInMusicProject/tasso-website/blob/gh-pages/data/indexes/rime-settings.aton

**Comment by craigsapp** [comment]
The original clef button is now working again on the work pages:

http://www.tassomusic.org/work/?id=Trm0047m

Music starts with modern clefs:

<img width="1084" alt="screen shot 2018-03-07 at 9 18 45 pm" src="https://user-images.githubusercontent.com/3487289/37134315-e074832e-224c-11e8-9b20-b07b05477ca6.png">

Clicking on the "o" button will highlight it and show the princeps clefs:

<img width="1097" alt="screen shot 2018-03-07 at 9 18 59 pm" src="https://user-images.githubusercontent.com/3487289/37134311-dc71d5ce-224c-11e8-979c-68d5140f0936.png">

Clicking "o" again will unhighlight it and return the clefs to modern style.

Of course, the "o" button will only work of there are original clefs listed in the score.  I will work on automating their insertion into the score from the data spreadsheets.   Here is what the original clefs encodings look like in the Humdrum scores:

https://github.com/TassoInMusicProject/tasso-scores/blob/a65da4247c225e9c260e3a5613025868c5a375e5/Trm/kern/Trm0047m-Non_e_questa_la_mano--Giovannelli_1588.krn#L18

The string `*oclefC3`, for example, means that the original clef for the music is a C clef on the third line from the bottom of the staff (alto clef).   The clef string on the following line: `*clefGv2` means a vocal tenor clef.  This is a G clef on the second staff line from the bottom of the staff, and the `v` means that the music is transposed down one octave from the written pitch.

The problem was caused by a change in how the verovio toolkit processes the XPath option in the input option object.  The name of the option was changed, but more importantly, the `appXPathQuery` option needs to be an array of strings (even if only one XPath query is given).

**Comment by craigsapp** [comment]
I have manually added the original clefs and mensurations to the newly added scores.  (I will sometime soon automate that process from the data on the spreadsheets).

The work Trm0318c does not have original clef information in the spreadsheet.

In Trm0333c the original mensuration for the Tenore part is Cut-C, so I made the modern key signature 2/1.
