### ISSUE TITLE
Put some more rime works online!

### ISSUE THREAD

**Issue by craigsapp** [TassoInMusicProject/tasso-website#77]
Trm0024a, Trm0048g, Trm1022a in particular.

**Comment by emilianoricciardi** [comment]
Thanks, Craig! Two small things about 1022a:

"Prima parte," Seconda parte, " etc. (this piece is in four parts) should
go above the staff, not below.

The last note of each section should be a long as if it were the end of a
piece (or a fermata, whichever we are doing at the end of pieces)

Emiliano

On Thu, Mar 8, 2018 at 12:33 AM, Craig Stuart Sapp <notifications@github.com
