### ISSUE TITLE
Text extraction tool sorting button

### ISSUE THREAD

**Issue by emilianoricciardi** [TassoInMusicProject/tasso-website#8]
Add "sort numerically' and "sort alphabetically" buttons to lyrics tool frequency table, such as on the page:

http://www.tassomusic.org/lyrics/?id=Trm0047m

sorted alphabetically by default:

<img width="1057" alt="screen shot 2017-03-31 at 8 00 06 am" src="https://cloud.githubusercontent.com/assets/3487289/24556113/2a906a80-15e8-11e7-99fd-2ec9e6d252d7.png">

sorting by count:

<img width="1067" alt="screen shot 2017-03-31 at 8 00 19 am" src="https://cloud.githubusercontent.com/assets/3487289/24556122/356cfd38-15e8-11e7-8627-a076829da671.png">

**Comment by craigsapp** [comment]
Implemented with commit: https://github.com/TassoInMusicProject/tasso-website/commit/d3b68a97ecdd399ecd3c373be749f4097a330ac5

Test page: http://www.tassomusic.org/lyrics/?id=Trm0047m

The Word Frequency table now has a button called "sort numerically" when the page is opened:

<img width="1059" alt="screen shot 2017-03-31 at 11 05 25 am" src="https://cloud.githubusercontent.com/assets/3487289/24563280/a1dd9d32-1602-11e7-9eca-7e11ceacad68.png">

When you click on that button (or anywhere in the horizontal region to the left), the word frequency data will be sorted into numerical order (highest counts first).  The button will then change to "sort alphabetically".

<img width="1052" alt="screen shot 2017-03-31 at 11 05 34 am" src="https://cloud.githubusercontent.com/assets/3487289/24563354/d9816ca0-1602-11e7-9ffa-f541d257e6c1.png">

And clicking on it will return to the alphabetical


In addition, a smaller button to the right of the sorting button, called "data", can be pressed to generate a plain text version of the tables that can be copied and pasted into other documents (excel, word, etc).  The data order matches that of the current table (sorted alphabetically or numerically):

<table><tr><td> <img src="https://cloud.githubusercontent.com/assets/3487289/24563424/10b79bd6-1603-11e7-8f1d-110c7091b12a.png"> </td><td> <img src="https://cloud.githubusercontent.com/assets/3487289/24563433/1893a0fc-1603-11e7-9073-0497d463035b.png"> </td></tr></table>

**Comment by emilianoricciardi** [comment]
Nice!

On Fri, Mar 31, 2017 at 1:23 PM, Craig Stuart Sapp <notifications@github.com
