### ISSUE TITLE
Highlight the text  when search for text on the workpage

### ISSUE THREAD

**Issue by craigsapp** [TassoInMusicProject/tasso-website#83]

**Comment by craigsapp** [comment]
Now implemented: searching for music will highlight music and searching for text will highlight text.

Example: http://www.tassomusic.org/work/?id=Trm0047c

<img width="1090" alt="screen shot 2018-03-07 at 9 08 21 pm" src="https://user-images.githubusercontent.com/3487289/37134028-4e841ae8-224b-11e8-9e60-40afa1b0056e.png">

each type of search is given a different color.

**Comment by emilianoricciardi** [comment]
This looks great!

On Thu, Mar 8, 2018 at 12:06 AM, Craig Stuart Sapp <notifications@github.com
