### ISSUE TITLE
Texts of Rime poems are not showing in the about pages

### ISSUE THREAD

**Issue by emilianoricciardi** [TassoInMusicProject/tasso-website#88]
This seems to have happened after we add a bunch of entries for the poems' About pages

**Comment by craigsapp** [comment]
This commit: https://github.com/TassoInMusicProject/tasso-website/commit/42ccc4b45f148d01735538885f1c3079a0b2baed
allows for empty translations; otherwise, the page was not being built when the poem did not have a translation.

Example:

http://www.tassomusic.org/poem/?rime=23

<img width="915" alt="screen shot 2018-03-21 at 5 41 20 pm" src="https://user-images.githubusercontent.com/3487289/37723429-aa372cfc-2d2e-11e8-9459-889a2e8c147d.png">

**Comment by craigsapp** [comment]
I also need to implement multi-verse poem display...

http://www.tassomusic.org/poem/?rime=126

<img width="915" alt="screen shot 2018-03-21 at 5 45 14 pm" src="https://user-images.githubusercontent.com/3487289/37723627-246220d6-2d2f-11e8-8341-904074df0be9.png">

**Comment by craigsapp** [comment]
Here is an initial implementation of multiple-verse poems:

http://www.tassomusic.org/poem/?rime=126

<img width="1216" alt="screen shot 2018-03-21 at 5 59 11 pm" src="https://user-images.githubusercontent.com/3487289/37724463-22bb3a54-2d31-11e8-82af-7d564d9a9cdc.png">

How should long lines be treated?  By shrinking the fontsize of all poems/translations, or by forcing a line wrap (probably with the wrapped text being indented a lot).

**Comment by emilianoricciardi** [comment]
Thanks, Craig! I think it's best to use a smaller font. Too many indents
make the poem hard to read.

Emiliano

**Comment by craigsapp** [comment]
I made the font smaller:

<img width="1055" alt="screen shot 2018-03-21 at 7 19 51 pm" src="https://user-images.githubusercontent.com/3487289/37729130-6c16ea6c-2d3c-11e8-8b7b-6b860b936ae7.png">

Probably if it is ever too long, then an indented line wrap could be the next step (but I don' t thing there are any at the moment).

Also: I enabled the next/previous single arrow buttons to browse through the poems (at the top of the page).

The double arrow is currently doing the same thing, but this will be changed to switch to musical settings, etc for a single poem.

**Comment by emilianoricciardi** [comment]
Hi Craig,

yes, this makes sense!

Emiliano

On Wed, Mar 21, 2018 at 2:20 PM, Craig Stuart Sapp <notifications@github.com

**Comment by emilianoricciardi** [comment]
Hi Craig,

some of the translations we will use are drawn from published sources, so
we want to add publication fields for translations as well. Should I do it
for all the poems, or just for those for which we will use published
translations? In the latter case, I can add the fields myself, I think.

Emiliano
